# Generated by Django 3.2.18 on 2023-05-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230504_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favourites',
        ),
    ]
