# Generated by Django 3.2.19 on 2023-06-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_makeup'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='makeup_products',
            field=models.TextField(blank=True),
        ),
    ]
