# Generated by Django 3.2.19 on 2023-06-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_makeup_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='makeup_products',
        ),
    ]
