# Generated by Django 3.2.19 on 2023-06-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
