# Generated by Django 3.2.19 on 2023-06-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_makeup_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='makeup_products',
            new_name='links',
        ),
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.TextField(blank=True),
        ),
    ]
