# Generated by Django 3.2.19 on 2023-06-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230629_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='links',
        ),
    ]
