# Generated by Django 3.2.19 on 2023-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230628_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='products',
        ),
        migrations.AddField(
            model_name='post',
            name='makeup',
            field=models.TextField(blank=True),
        ),
    ]
