# Generated by Django 3.2.19 on 2023-06-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230628_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='makeup_links',
            field=models.TextField(blank=True),
        ),
    ]
