# Generated by Django 3.2.19 on 2023-06-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230628_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='product_links',
        ),
        migrations.AddField(
            model_name='post',
            name='makeup_links',
            field=models.URLField(blank=True),
        ),
    ]
