# Generated by Django 3.2.19 on 2023-06-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230628_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='makeup',
            field=models.TextField(blank=True),
        ),
    ]
