# Generated by Django 3.2.19 on 2023-06-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_makeup_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='makeup',
        ),
    ]
