# Generated by Django 3.2.19 on 2023-06-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_favourites'),
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pin',
            unique_together={('post',)},
        ),
    ]
