# Generated by Django 3.2.19 on 2023-06-18 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_favourites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pins', '0002_alter_pin_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pin',
            unique_together={('owner', 'post')},
        ),
    ]
